import os

from dotenv import load_dotenv

load_dotenv()

# Telegram bot token
TOKEN = os.getenv("BOT_TOKEN", "")  # Bot Token generated by Telegram BotFather

# URL for the appointment slots
URL = os.getenv(
    "URL",
    "https://esii-orion.com/orion-reservation/slots?account=EVMSPI&config=SEJOURREMISE&usemode=app",
)

# Default frequency for checking appointments in seconds
DEFAULT_FREQUENCY = int(
    os.getenv("DEFAULT_FREQUENCY", 1800)
)  # 30min (WARNING !!! A too high frequency can be considered as a DOS attack, be careful)

# Path to Chromium executable
CHROMIUM_PATH = os.getenv(
    "PUPPETEER_EXECUTABLE_PATH",
    "/usr/bin/chromium",
)
