version: '3.8'

services:
  app:
    build: .
    container_name: rdv-app
    ports:
      - "5000:5000"
    environment:
      - URL=${URL}
      - DEFAULT_FREQUENCY=${DEFAULT_FREQUENCY}
      - CHROMIUM_PATH=${CHROMIUM_PATH}
    volumes:
      - .:/app
    command: >
      sh -c "flask run --host=0.0.0.0 --port=5000"
